### ISSUE TITLE
Feature Request: add VLAN support

### ISSUE THREAD

**Issue by jchurchward** [aceberg/WatchYourLAN#34]
I am sure this has been asked many times already, but I couldn't see it here. Is VLAN support able to be added this would be amazing to sit across multiple VLANs, that and or ability to integrate with Unifi API and pull the data from there.

**Comment by markus-li** [comment]
The way I see it, for VLAN checks it would "just" need a config entry for allowed VLAN ids and then run arp-scan with the --vlan tag for each and every vlan specified. Outside of that it would be a matter of watching for traffic on any vlans not allowed and alert that there's an unknown vlan in use. Since adding VLANs is not a common occurrence in any network there should be no need for a UI component, only a config file entry.

**Comment by jchurchward** [comment]
Excellent that sounds easy enough then. hopefully the developer will see this and share some thoughts on the topic and can make it work 👍

**Comment by thehijacker** [comment]
Another vote on this. To add additional subnets. Like:

192.168.28.0/24 - eth0
10.0.107.0/24 - eth1 - vlan 107
10.0.208.0/24 - eth0 - vlan 208

Command line would be for example:

arp-scan --ignoredups --retry=6 192.168.28.0/24 --interface=eth0
arp-scan --ignoredups --retry=6 10.0.107.0/24 --vlan=107 --interface=eth1
arp-scan --ignoredups --retry=6 10.0.208.0/24 --vlan=208 --interface=eth0

This works and returns devices. Can you please support this function in GUI configuration?

**Comment by GentleHoneyLover** [comment]
+1. Love the tool! Adding VLAN support would make it absolutely perfect for the its use case!

**Comment by tonicb78** [comment]
+1

**Comment by armond-avanes** [comment]
+1

**Comment by aceberg** [comment]
Done in v2. Here is how-to: https://github.com/aceberg/WatchYourLAN/blob/main/docs/VLAN_ARP_SCAN.md#3-arp_strs-for-vlans-docker0-and-other-complicated-scans
